main: me.indian.example.ServerConnectionExampleNukkit
name: ServerConnectionExample
authors: [ IndianPL ]
description: ServerConnectionExample plugin
version: '${project.version}'
depend:
  - ServerConnect
  - PlaceholderAPI
api: [ "1.0.14" ]
